services:
  # A Docker web service
  - type: web
    name: manim-video-api
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        value: sk_36f5869464efc9e2d89d63404d872bbe775e820619829c05
      - key: ALLOWED_ORIGINS
        value: https://intellect-app.vercel.app,http://localhost:3000
